config/routes.rb
Rails.application.routes.draw do
  resources :articles

end

app/models/article.rb
class Article < ActiveRecord::Base
	mount_uploader :local_audio, AudioFileUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
	skip_before_action :verify_authenticity_token, if: :json_request?, only: [:update, :new, :create]

  # GET /articles
  # GET /articles.json
  def index
		if params[:process] == "true"
			@article = Article.find_by(status: nil)
			if not @article
				@article = Article.find_by(status: "")
			end

			if @article
				redirect_to action: "edit", id: @article.id, format: params[:format]
			else
				respond_to do |format|
					format.html { render :no_more_articles }
					format.json { render json: "no more articles" }
				end
			end
		else
			@article = Article.new
			@stickedArticles = Article.where(sticked: true).order(created_at: :desc).all
			@noneStickedArticles = Article.where(sticked: false).order(created_at: :desc).all
		end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
		respond_to do |format|
			format.html
			format.json { render json: @article }
		end
  end

  # GET /articles/1/edit
  def edit
		respond_to do |format|
			format.html
			format.json { render json: @article }
		end
  end

  # POST /articles
  # POST /articles.json
  def create
		# delete expire article
		if Article.count > 40
			Article.where(sticked: false).order(:created_at).first.destroy
		end

    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
				ActionCable.server.broadcast 'new_article', id: @article.id
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
			stickedPost = @article.sticked
      if @article.update(article_params)
				if (params[:article][:sticked] == "true") == stickedPost
					if params[:article][:status] == "Finished"
						ActionCable.server.broadcast 'messages',
							id: @article.id
					else
						ActionCable.server.broadcast 'new_article',
							id: @article.id
					end
					format.html { redirect_to @article, notice: 'Article was successfully updated.' }
					format.json { render :show, status: :ok, location: @article }
				else
					format.js	{}
					format.html { redirect_to articles_url, notice: 'Article stick state was successfully updated.' }
				end
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:source_url, :title, :text_content, :local_audio, :audio_file_url, :sentence_time, :status, :sticked)
    end

		def json_request?
			request.format.json?
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article_item.html.erb
<% articles.each do |article| %>
	<tr id="<%= article.id %>">
		<td><%= link_to article.title, article %></td>
		<td><%= article.status %></td>
		<td>
			<%= link_to 'Show', article %>
			<%= link_to 'Edit', edit_article_path(article) %>
			<%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %>
			<%= form_for(article, method: :patch, remote: true) do |f| %>
				<div class="field">
					<% if article.sticked == true %>
						<%= f.hidden_field(:sticked, value: false) %>
					<% else %>
						<%= f.hidden_field(:sticked, value: true) %>
					<%end %>
				</div>
				<% if article.sticked == true %>
					<div class="actions sticked_button">
						<%= submit_tag "取消置顶" %>
					</div>
				<% else %>
					<div class="actions">
						<%= submit_tag "设置置顶" %>
					</div>
				<%end %>
			<% end %>
		</td>
	</tr>
<% end %>

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :source_url %><br>
    <%= f.text_area :source_url %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_area :title %>
  </div>
  <div class="field">
    <%= f.label :text_content %><br>
    <%= f.text_area :text_content %>
  </div>
  <div class="field">
    <%= f.label :local_audio %><br>
    <%= f.file_field :local_audio %>
  </div>
  <div class="field">
    <%= f.label :audio_file_url %><br>
    <%= f.text_area :audio_file_url %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
	<div class="field">
		<%= f.hidden_field :sticked, value: @article.sticked %>
	</div>
	 <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/_hide_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "请输入网址或需要朗读的文本：" %><br>
    <%= f.text_area :source_url %>
  </div>
  <div class="field">
		<%= hidden_field(:article, :title) %>
		<%= hidden_field(:article, :text_content) %>
		<%= hidden_field(:article, :local_audio) %>
		<%= hidden_field(:article, :audio_file_url) %>
		<%= hidden_field(:article, :status) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Articles</h1>

<%= render 'hide_form' %>
<br>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Status</th>
      <th>Operation</th>
    </tr>
  </thead>
  <tbody id="sticked_articles">
		<%= render partial: 'article_item', locals:{ articles:@stickedArticles } %>
  </tbody>
  <tbody id="none_sticked_articles">
		<%= render partial: 'article_item', locals:{ articles:@noneStickedArticles } %>
  </tbody>
</table>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/no_more_articles.html.erb
<p id="notice"><%= notice %></p>

<p>
	all articles has been processed.
</p>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Source url:</strong>
	<a href="<%=@article.source_url%>" target="_blank"><u style="word-break:break-all;word-wrap:break-word;color:blue;margin-left:2em;">打 开 原 网 页</u></a>
</p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<% if (!@article.local_audio_url.nil? && !@article.local_audio_url.blank?) %>
	<div id="audio_player_div">
		<audio id="audio_player" class="article_audio" src="<%= @article.local_audio_url %>" controls="controls"/>
	</div>
<% else %>
	<div class="spinner">
		<div class="bounce1"></div>
		<div class="bounce2"></div>
		<div class="bounce3"></div>
	</div>
<% end %>

<p>
  <strong>Text content:</strong>
  <%= raw @article.text_content %>
</p>

<p>
  <strong>Audio file url:</strong>
  <%= link_to "Download file", @article.local_audio_url %>
  <%= @article.audio_file_url %>
</p>
<p>
  <strong>Status:</strong>
	<strong id="status" data-target-id=<%=@article.id%>><%= @article.status %></strong>
</p>
<% if(!@article.sentence_time.nil? && !@article.sentence_time.blank?) %>
	<script type="text/javascript">
		sentenceTimeArray = [<%= @article.sentence_time %>]
	</script>
<% end %>
<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/articles/update.js.erb
<% if @article.sticked == true %>
	$("#<%=@article.id%> .actions").addClass("sticked_button");
	$("#<%=@article.id%>").appendTo("#sticked_articles");
	$("#<%=@article.id%> input[name='article[sticked]']").attr("value","false")
<% else %>
	$("#<%=@article.id%> .actions").removeClass("sticked_button");
	$("#<%=@article.id%>").appendTo("#none_sticked_articles");
	$("#<%=@article.id%> input[name='article[sticked]']").attr("value","true")
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta name="renderer" content="webkit|ie-comp|ie-stand">
	<meta http-equiv="X-UA-Compatible" content="chrome=1,IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
	<%= favicon_link_tag %>
	<% #for 360browser %>
	<%= favicon_link_tag "favicon.ico", rel:"icon" %>
	<title>EzListen</title>
</head>
<body id="<%=params[:controller]+"-"+params[:action]%>">
	<%= yield %>
	<h1><%= debug(params) if Rails.env.development? %></h1>
</body>
</html>